#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d  '' '󰲠' '󰲢' '󰲤' '󰲦' '󰲨'
#bspc monitor -d file terminal code browser social music

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#~/.config/polybar/launch.sh &
xsetroot -cursor_name left_ptr &

eww open launcher
eww open clock
eww open sys
eww open system

$HOME/.config/eww/xworkspaces/xprofile &
